Modify the git commit message template to adhere to new standards
Changelog:
 - `Git/commit-message-template.txt` modified.
 - renamed the template because of the spelling
   error: message not massage
 - Added the commit template configuration to both `.gitconfig` files
 - Added a `README.md` to the git configs to explain how to use those
   configurations.

Tag: feature